# -*- mode: ruby -*-
# vi: set ft=ruby :


servers = {
  :hadoop1 => '192.168.33.10',
}

Vagrant.configure(2) do |config|
  config.vm.box = "centos71" #"ubuntu.server1404.100g"

  servers.each do |server_name, server_ip|
    config.vm.define server_name do |server_config|
      server_config.vm.hostname = server_name
      server_config.vm.network "private_network", ip: server_ip
      config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 3
      end
      config.vm.synced_folder "installer", "/installer"
      config.vm.provision "shell", path: "setup_spark_pseudo.sh"
    end
  end
end

