# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu.server1404" #"ubuntu.server1404.100g"
  config.ssh.insert_key = false
  
  config.vm.define "server01" do |server01|
    server01.vm.hostname = "server01"
    server01.vm.network :private_network, ip: "192.168.11.61"
    server01.vm.provision :shell, path: "resources/setup.sh"
  end
  
  config.vm.define "server02" do |server02|
    server02.vm.hostname = "server02"
    server02.vm.network :private_network, ip: "192.168.11.62"
    server02.vm.provision :shell, path: "resources/setup.sh"
  end
  
  config.vm.define "server03" do |server03|
    server03.vm.hostname = "server03"
    server03.vm.network :private_network, ip: "192.168.11.63"
    server03.vm.provision :shell, path: "resources/setup.sh"
  end
end

