# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu.server1404"
  config.ssh.insert_key = false
  
  File.open("resources/hosts", "r") do |file_handle|
    count = file_handle.count
    file_handle.rewind
    file_handle.each_with_index do |server, index|
      config.vm.define server.split(' ').last do |host|
	    host.vm.hostname = server.split(' ')[1]
        host.vm.network :private_network, ip: server.split(' ').first
        host.vm.provision :shell, path: "resources/setup.sh"
      end
    end
  end
end

