# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.insert_key = false
  
  config.vm.define "server01" do |server01|
    server01.vm.hostname = "server01"
    server01.vm.network :private_network, ip: "192.168.11.51"
    server01.vm.network :private_network, ip: "192.168.12.51", virtualbox__intnet: true
    server01.vm.provision :shell, path: "resources/provision.sh"
  end

  config.vm.define "server02" do |server02|
    server02.vm.hostname = "server02"
    server02.vm.network :private_network, ip: "192.168.11.51"
    server02.vm.network :private_network, ip: "192.168.12.52", virtualbox__intnet: true
    server02.vm.provision :shell, path: "resources/provision.sh"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "256"
    vb.cpus = 2
  end
end
