# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.ssh.insert_key = false
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
    vb.cpus = 2
  end

  config.vm.define "server01" do |server01|
    server01.vm.hostname = "server01"
    server01.vm.provision :shell, path: "resources/setup.sh"
  end
end
