# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu.server1404.100g"
  config.ssh.insert_key = false

  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network :private_network, ip: "192.168.11.51"
    master.vm.provision :shell, path: "resources/setup.sh"
  end

  config.vm.define "slave" do |slave|
    slave.vm.hostname = "slave"
    slave.vm.network :private_network, ip: "192.168.11.52"
    slave.vm.provision :shell, path: "resources/setup.sh"
  end
end

