# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu.server1404.100g"
  config.vm.provision "shell" do |s|
    s.path = "resources/setup.sh"
  end
end

